package agentfox

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/agent-fox-dev/agentfox/afspec"
)

// navigationBaseline is docs/development.md's Navigation baseline section, up
// to the next second-level heading.
func navigationBaseline(t *testing.T) string {
	t.Helper()
	content := readDoc(t, "development.md")
	_, section, ok := strings.Cut(content, "\n## Navigation baseline\n")
	if !ok {
		t.Fatal("docs/development.md has no '## Navigation baseline' section")
	}
	if end := strings.Index(section, "\n## "); end >= 0 {
		section = section[:end]
	}
	return section
}

// baselineRunRe is one run of the procedure: a tool, --dry-run, and the fixed
// input under $B (testdata/baseline) as its last argument.
var baselineRunRe = regexp.MustCompile(`(?m)^(triage|fix|spec|impl) --dry-run .*"\$B/([^"]+)"\s*$`)

// TS-13-33 (unit): docs/development.md contains the Navigation baseline
// section with procedure, tables and regeneration note
// Verifies: 13-REQ-9.1, 13-REQ-9.2, 13-REQ-9.3
//
// The tool the spec calls `issue` is `triage` today
// (docs/errata/13_navigation_baseline.md), so the procedure is checked for
// triage, fix, spec and impl.
func TestTS_13_33_NavigationBaselineSection(t *testing.T) {
	section := navigationBaseline(t)
	root := findWorkspaceRoot(t)

	// 13-REQ-9.1: the procedure and its fixed inputs.
	inputs := baselineInputs(t, section, filepath.Join(root, "testdata", "baseline"))
	checkBaselineSeed(t, section, root, inputs["fix"])
	checkBaselineImplInput(t, root, inputs["impl"])

	// 13-REQ-9.2: one table per tool.
	checkBaselineTables(t, section)

	// 13-REQ-9.3: regenerated by hand, and no live-model run in make test.
	if !strings.Contains(section, "regenerated by hand") {
		t.Error("the section does not say the tables are regenerated by hand")
	}
	if !strings.Contains(section, "No live-model run enters `make test`") {
		t.Error("the section does not say that no live-model run enters make test")
	}

	// The spec's `issue` is today's triage, and the section says so.
	if !strings.Contains(section, "errata/13_navigation_baseline.md") {
		t.Error("the section does not point at the erratum that maps the spec's `issue` to triage")
	}
	erratum, err := os.ReadFile(filepath.Join(root, "docs", "errata", "13_navigation_baseline.md"))
	if err != nil {
		t.Fatalf("reading the erratum: %v", err)
	}
	if !strings.Contains(string(erratum), "`issue`") || !strings.Contains(string(erratum), "`triage`") {
		t.Error("the erratum does not record that the spec's `issue` is `triage`")
	}
}

// baselineInputs checks that the procedure runs a fixed set of inputs per
// tool with --dry-run (two for triage, two for fix, three for spec, one for
// impl), in a throwaway clone, that every input exists, and that the triage
// inputs are a stack trace and a prose report. It returns the inputs by tool,
// relative to baseline.
func baselineInputs(t *testing.T, section, baseline string) map[string][]string {
	t.Helper()
	inputs := map[string][]string{}
	for _, m := range baselineRunRe.FindAllStringSubmatch(section, -1) {
		inputs[m[1]] = append(inputs[m[1]], m[2])
	}
	for tool, want := range map[string]int{"triage": 2, "fix": 2, "spec": 3, "impl": 1} {
		if got := len(inputs[tool]); got != want {
			t.Errorf("the procedure runs `%s --dry-run` on %d fixed input(s) %v, want %d", tool, got, inputs[tool], want)
		}
		for _, in := range inputs[tool] {
			if _, err := os.Stat(filepath.Join(baseline, in)); err != nil {
				t.Errorf("the procedure's %s input testdata/baseline/%s is missing: %v", tool, in, err)
			}
		}
	}
	if !strings.Contains(section, "git clone . ") {
		t.Error("the procedure does not run fix and impl in a throwaway clone")
	}

	var traces int
	for _, in := range inputs["triage"] {
		b, err := os.ReadFile(filepath.Join(baseline, in))
		if err == nil && strings.Contains(string(b), "goroutine ") && strings.Contains(string(b), "panic: ") {
			traces++
		}
	}
	if traces != 1 {
		t.Errorf("%d of the triage inputs %v are stack traces, want one stack trace and one prose report",
			traces, inputs["triage"])
	}
	return inputs
}

// checkBaselineSeed checks that the fix inputs name a defect the procedure
// seeds, and that the seed still applies to this tree.
func checkBaselineSeed(t *testing.T, section, root string, fixInputs []string) {
	t.Helper()
	if !strings.Contains(section, `git apply "$B/fix/seed.patch"`) {
		t.Error("the procedure does not seed the defect the fix inputs name")
	}
	if _, err := exec.LookPath("git"); err == nil {
		seed := filepath.Join(root, "testdata", "baseline", "fix", "seed.patch")
		if out, err := exec.Command("git", "-C", root, "apply", "--check", seed).CombinedOutput(); err != nil {
			t.Errorf("testdata/baseline/fix/seed.patch no longer applies; regenerate it against the "+
				"current issuex/parse.go: %v\n%s", err, out)
		}
	}
	for _, in := range fixInputs {
		b, err := os.ReadFile(filepath.Join(root, "testdata", "baseline", in))
		if err != nil || !strings.Contains(string(b), "ParseRemote") && !strings.Contains(string(b), "subgroup") {
			t.Errorf("the fix input testdata/baseline/%s does not name the seeded defect", in)
		}
	}
}

// checkBaselineImplInput checks that the impl input is a spec package of at
// least three tasks that impl would accept.
func checkBaselineImplInput(t *testing.T, root string, implInputs []string) {
	t.Helper()
	for _, in := range implInputs {
		s, err := afspec.LoadSpec(filepath.Join(root, "testdata", "baseline", in))
		if err != nil {
			t.Errorf("the impl input testdata/baseline/%s does not load: %v", in, err)
			continue
		}
		if r := s.Validate(); !r.Valid {
			t.Errorf("the impl input testdata/baseline/%s does not validate: %v", in,
				afspec.FormatValidationEntries(r.Errors))
		}
		if n := len(s.Tasks.Tasks); n < 3 {
			t.Errorf("the impl input testdata/baseline/%s has %d task(s), want at least three", in, n)
		}
	}
}

// checkBaselineTables checks for one table per tool of the per-phase
// tool_calls, with a column per navigation tool and a row for each phase the
// tool records, under the name it records it.
func checkBaselineTables(t *testing.T, section string) {
	t.Helper()
	if !strings.Contains(section, ".tool_calls") {
		t.Error("the section does not say the counts are the envelope's tool_calls")
	}
	phases := map[string][]string{
		"triage": {"triage"},
		"fix":    {"analyse", "implement"},
		"spec":   {"prd", "generate:requirements", "generate:test_spec", "generate:tasks"},
		"impl":   {"survey", "implement (task 1)", "implement (task 2)", "implement (task 3)", "review"},
	}
	for tool, names := range phases {
		_, table, ok := strings.Cut(section, "\n#### "+tool+"\n")
		if !ok {
			t.Errorf("the section has no table for %s", tool)
			continue
		}
		if end := strings.Index(table, "\n#"); end >= 0 {
			table = table[:end]
		}
		if !strings.Contains(table, "| read_file | list_files | find_files | search_files |") {
			t.Errorf("the %s table does not have a column per navigation tool", tool)
		}
		for _, name := range names {
			if !strings.Contains(table, "| "+name+" |") {
				t.Errorf("the %s table has no row for its %q phase", tool, name)
			}
		}
	}
}
