package agentfox

import (
	"strings"
	"testing"
)

// TS-13-33 (unit): docs/development.md contains the Navigation baseline
// section with procedure, tables and regeneration note
// Verifies: 13-REQ-9.1, 13-REQ-9.2, 13-REQ-9.3
func TestTS_13_33_NavigationBaselineSection(t *testing.T) {
	content := readDoc(t, "development.md")

	// 13-REQ-9.1: contains a 'Navigation baseline' section heading
	if !strings.Contains(content, "Navigation baseline") {
		t.Error("docs/development.md has no 'Navigation baseline' section")
	}

	// 13-REQ-9.1: contains a procedure mentioning --dry-run and fixed inputs
	// for issue, fix, spec and impl
	if !strings.Contains(content, "--dry-run") {
		t.Error("docs/development.md does not mention --dry-run in the Navigation baseline section")
	}
	for _, tool := range []string{"issue", "fix", "spec", "impl"} {
		if !strings.Contains(content, tool) {
			t.Errorf("docs/development.md does not mention tool %q in the Navigation baseline section", tool)
		}
	}

	// 13-REQ-9.2: contains at least one table with tool_calls data
	if !strings.Contains(content, "tool_calls") {
		t.Error("docs/development.md does not contain tool_calls data")
	}

	// 13-REQ-9.3: contains a note about regenerating tables by hand and no
	// live-model run entering make test
	if !strings.Contains(content, "regenerated by hand") {
		t.Error("docs/development.md does not mention tables being regenerated by hand")
	}
	if !strings.Contains(content, "make test") {
		t.Error("docs/development.md does not mention make test in the regeneration note")
	}
}
