// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package afspec

// Schema for the YAML frontmatter block in prd.md (format version 2)
type PrdFrontmatterV2Json struct {
	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// IntentHash corresponds to the JSON schema field "intent_hash".
	IntentHash PrdFrontmatterV2JsonIntentHash `json:"intent_hash" yaml:"intent_hash" mapstructure:"intent_hash"`

	// Owner corresponds to the JSON schema field "owner".
	Owner *string `json:"owner,omitempty,omitzero" yaml:"owner,omitempty" mapstructure:"owner,omitempty"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// Source corresponds to the JSON schema field "source".
	Source *string `json:"source,omitempty,omitzero" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// SpecId corresponds to the JSON schema field "spec_id".
	SpecId string `json:"spec_id" yaml:"spec_id" mapstructure:"spec_id"`

	// SpecName corresponds to the JSON schema field "spec_name".
	SpecName string `json:"spec_name" yaml:"spec_name" mapstructure:"spec_name"`

	// Status corresponds to the JSON schema field "status".
	Status PrdFrontmatterV2JsonStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Supersedes corresponds to the JSON schema field "supersedes".
	Supersedes []string `json:"supersedes,omitempty,omitzero" yaml:"supersedes,omitempty" mapstructure:"supersedes,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt string `json:"updated_at" yaml:"updated_at" mapstructure:"updated_at"`
}

type PrdFrontmatterV2JsonIntentHash *string

type PrdFrontmatterV2JsonStatus string

const PrdFrontmatterV2JsonStatusActive PrdFrontmatterV2JsonStatus = "active"
const PrdFrontmatterV2JsonStatusArchived PrdFrontmatterV2JsonStatus = "archived"
const PrdFrontmatterV2JsonStatusDraft PrdFrontmatterV2JsonStatus = "draft"
const PrdFrontmatterV2JsonStatusSealed PrdFrontmatterV2JsonStatus = "sealed"
const PrdFrontmatterV2JsonStatusSuperseded PrdFrontmatterV2JsonStatus = "superseded"
