// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package afspec

// One EARS statement. The rendered sentence is derived from pattern, condition,
// guard, system and action.
type Criterion struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action" yaml:"action" mapstructure:"action"`

	// The WHEN / WHILE / IF / WHERE clause. Absent for ubiquitous.
	Condition *string `json:"condition,omitempty,omitzero" yaml:"condition,omitempty" mapstructure:"condition,omitempty"`

	// What the caller observes. Required for unwanted.
	Contract *string `json:"contract,omitempty,omitzero" yaml:"contract,omitempty" mapstructure:"contract,omitempty"`

	// The AND clause. complex_event only.
	Guard *string `json:"guard,omitempty,omitzero" yaml:"guard,omitempty" mapstructure:"guard,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Pattern corresponds to the JSON schema field "pattern".
	Pattern CriterionPattern `json:"pattern" yaml:"pattern" mapstructure:"pattern"`

	// The acting component. Defaults to "system" when rendering.
	System *string `json:"system,omitempty,omitzero" yaml:"system,omitempty" mapstructure:"system,omitempty"`
}

type CriterionPattern string

const CriterionPatternComplexEvent CriterionPattern = "complex_event"
const CriterionPatternEventDriven CriterionPattern = "event_driven"
const CriterionPatternOptional CriterionPattern = "optional"
const CriterionPatternStateDriven CriterionPattern = "state_driven"
const CriterionPatternUbiquitous CriterionPattern = "ubiquitous"
const CriterionPatternUnwanted CriterionPattern = "unwanted"

type ExecutionPath struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Steps corresponds to the JSON schema field "steps".
	Steps []PathStep `json:"steps" yaml:"steps" mapstructure:"steps"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

type ExternalApi struct {
	// Package corresponds to the JSON schema field "package".
	Package string `json:"package" yaml:"package" mapstructure:"package"`

	// Symbols corresponds to the JSON schema field "symbols".
	Symbols []ExternalApiSymbol `json:"symbols" yaml:"symbols" mapstructure:"symbols"`

	// Verified corresponds to the JSON schema field "verified".
	Verified bool `json:"verified" yaml:"verified" mapstructure:"verified"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type ExternalApiSymbol struct {
	// ImportPath corresponds to the JSON schema field "import_path".
	ImportPath string `json:"import_path" yaml:"import_path" mapstructure:"import_path"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Notes corresponds to the JSON schema field "notes".
	Notes *string `json:"notes,omitempty,omitzero" yaml:"notes,omitempty" mapstructure:"notes,omitempty"`

	// Signature corresponds to the JSON schema field "signature".
	Signature string `json:"signature" yaml:"signature" mapstructure:"signature"`
}

type PathStep struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action" yaml:"action" mapstructure:"action"`

	// Actor corresponds to the JSON schema field "actor".
	Actor string `json:"actor" yaml:"actor" mapstructure:"actor"`
}

type Requirement struct {
	// Criteria corresponds to the JSON schema field "criteria".
	Criteria []Criterion `json:"criteria" yaml:"criteria" mapstructure:"criteria"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Rationale corresponds to the JSON schema field "rationale".
	Rationale *string `json:"rationale,omitempty,omitzero" yaml:"rationale,omitempty" mapstructure:"rationale,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

// Schema for requirements.json spec artifact (format version 2)
type RequirementsV2Json struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema string `json:"$schema" yaml:"$schema" mapstructure:"$schema"`

	// ExecutionPaths corresponds to the JSON schema field "execution_paths".
	ExecutionPaths []ExecutionPath `json:"execution_paths" yaml:"execution_paths" mapstructure:"execution_paths"`

	// ExternalApis corresponds to the JSON schema field "external_apis".
	ExternalApis []ExternalApi `json:"external_apis,omitempty,omitzero" yaml:"external_apis,omitempty" mapstructure:"external_apis,omitempty"`

	// Glossary corresponds to the JSON schema field "glossary".
	Glossary RequirementsV2JsonGlossary `json:"glossary,omitempty,omitzero" yaml:"glossary,omitempty" mapstructure:"glossary,omitempty"`

	// Introduction corresponds to the JSON schema field "introduction".
	Introduction string `json:"introduction" yaml:"introduction" mapstructure:"introduction"`

	// Requirements corresponds to the JSON schema field "requirements".
	Requirements []Requirement `json:"requirements" yaml:"requirements" mapstructure:"requirements"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// SpecId corresponds to the JSON schema field "spec_id".
	SpecId string `json:"spec_id" yaml:"spec_id" mapstructure:"spec_id"`

	// SpecName corresponds to the JSON schema field "spec_name".
	SpecName string `json:"spec_name" yaml:"spec_name" mapstructure:"spec_name"`
}

type RequirementsV2JsonGlossary map[string]string
