// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package afspec

type Dependency struct {
	// Reason corresponds to the JSON schema field "reason".
	Reason string `json:"reason" yaml:"reason" mapstructure:"reason"`

	// Spec corresponds to the JSON schema field "spec".
	Spec string `json:"spec" yaml:"spec" mapstructure:"spec"`
}

type Task struct {
	// Criteria corresponds to the JSON schema field "criteria".
	Criteria []string `json:"criteria,omitempty,omitzero" yaml:"criteria,omitempty" mapstructure:"criteria,omitempty"`

	// DependsOn corresponds to the JSON schema field "depends_on".
	DependsOn []int `json:"depends_on,omitempty,omitzero" yaml:"depends_on,omitempty" mapstructure:"depends_on,omitempty"`

	// DoneWhen corresponds to the JSON schema field "done_when".
	DoneWhen []string `json:"done_when,omitempty,omitzero" yaml:"done_when,omitempty" mapstructure:"done_when,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id int `json:"id" yaml:"id" mapstructure:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind TaskKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Optional corresponds to the JSON schema field "optional".
	Optional *bool `json:"optional,omitempty,omitzero" yaml:"optional,omitempty" mapstructure:"optional,omitempty"`

	// State corresponds to the JSON schema field "state".
	State TaskState `json:"state" yaml:"state" mapstructure:"state"`

	// Steps corresponds to the JSON schema field "steps".
	Steps []string `json:"steps" yaml:"steps" mapstructure:"steps"`

	// Tests corresponds to the JSON schema field "tests".
	Tests []string `json:"tests" yaml:"tests" mapstructure:"tests"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// Touches corresponds to the JSON schema field "touches".
	Touches []string `json:"touches,omitempty,omitzero" yaml:"touches,omitempty" mapstructure:"touches,omitempty"`
}

type TaskKind string

const TaskKindImplement TaskKind = "implement"
const TaskKindIntegration TaskKind = "integration"

type TaskState string

const TaskStateDone TaskState = "done"
const TaskStateDropped TaskState = "dropped"
const TaskStateInProgress TaskState = "in_progress"
const TaskStatePending TaskState = "pending"

// Schema for tasks.json spec artifact (format version 2)
type TasksV2Json struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema string `json:"$schema" yaml:"$schema" mapstructure:"$schema"`

	// Dependencies corresponds to the JSON schema field "dependencies".
	Dependencies []Dependency `json:"dependencies" yaml:"dependencies" mapstructure:"dependencies"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// SpecId corresponds to the JSON schema field "spec_id".
	SpecId string `json:"spec_id" yaml:"spec_id" mapstructure:"spec_id"`

	// SpecName corresponds to the JSON schema field "spec_name".
	SpecName string `json:"spec_name" yaml:"spec_name" mapstructure:"spec_name"`

	// Tasks corresponds to the JSON schema field "tasks".
	Tasks []Task `json:"tasks" yaml:"tasks" mapstructure:"tasks"`

	// TestCommands corresponds to the JSON schema field "test_commands".
	TestCommands TestCommands `json:"test_commands" yaml:"test_commands" mapstructure:"test_commands"`
}

type TestCommands struct {
	// AllTests corresponds to the JSON schema field "all_tests".
	AllTests string `json:"all_tests" yaml:"all_tests" mapstructure:"all_tests"`

	// Linter corresponds to the JSON schema field "linter".
	Linter string `json:"linter" yaml:"linter" mapstructure:"linter"`

	// SpecTests corresponds to the JSON schema field "spec_tests".
	SpecTests *string `json:"spec_tests,omitempty,omitzero" yaml:"spec_tests,omitempty" mapstructure:"spec_tests,omitempty"`
}
