// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package afspec

type Test struct {
	// Given corresponds to the JSON schema field "given".
	Given []string `json:"given" yaml:"given" mapstructure:"given"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind TestKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Pseudocode corresponds to the JSON schema field "pseudocode".
	Pseudocode *string `json:"pseudocode,omitempty,omitzero" yaml:"pseudocode,omitempty" mapstructure:"pseudocode,omitempty"`

	// RealComponents corresponds to the JSON schema field "real_components".
	RealComponents []string `json:"real_components,omitempty,omitzero" yaml:"real_components,omitempty" mapstructure:"real_components,omitempty"`

	// Then corresponds to the JSON schema field "then".
	Then []string `json:"then" yaml:"then" mapstructure:"then"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// Verifies corresponds to the JSON schema field "verifies".
	Verifies []string `json:"verifies" yaml:"verifies" mapstructure:"verifies"`

	// When corresponds to the JSON schema field "when".
	When string `json:"when" yaml:"when" mapstructure:"when"`
}

type TestKind string

const TestKindIntegration TestKind = "integration"
const TestKindProperty TestKind = "property"
const TestKindSmoke TestKind = "smoke"
const TestKindUnit TestKind = "unit"

// Schema for test_spec.json spec artifact (format version 2)
type TestSpecV2Json struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema string `json:"$schema" yaml:"$schema" mapstructure:"$schema"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// SpecId corresponds to the JSON schema field "spec_id".
	SpecId string `json:"spec_id" yaml:"spec_id" mapstructure:"spec_id"`

	// SpecName corresponds to the JSON schema field "spec_name".
	SpecName string `json:"spec_name" yaml:"spec_name" mapstructure:"spec_name"`

	// Tests corresponds to the JSON schema field "tests".
	Tests []Test `json:"tests" yaml:"tests" mapstructure:"tests"`
}
